### ISSUE TITLE
[vwc-datepicker & vwc-accordion clash]

### ISSUE THREAD

**Issue by jfedoruk** [Vonage/vivid#1212]
**Describe the bug**
Accordion close by itself after using date picker.

**To Reproduce**
Go to User Admin -> Schedules -> https://itg-test.nvmtest.net/CallCentre/portal/useradmin/schedules/
Open "Create schedule" or edit existing one
Expand "Rules" section
Click on a time to show time selector
Choose some time and click outside the selector/press Esc/press Enter

**Expected behavior**
Accordion should still be expanded, because after choosing the time user wants to choose the day/days

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Windows 10
Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Additional context**
Use the same credentials for UserAdmin as before - user testUserVivid.

**Comment by yinonov** [comment]
This is caused due to both component sharing the exact same event firing name of _closed_
https://github.com/Vonage/vivid/blob/31c06c0afb665c0139f0f9f677b7489891267257/components/expansion-panel/src/vwc-expansion-panel-base.ts#L46

@Vonage/vivid-core as accordion, expansion-panel & datepicker are all in _alpha_ state, it's possible to apply namespace to custom fired events as in #1199 

@jfedoruk in the meantime can you workaround this with
```js
{datepicker}.addEventListener('closed', (e) => {
  e.stopPropagation(); 
});
```
and
```js
{expansion-panel}.addEventListener('closed', function(e) { 
  if (e.target !== this) {
    console.log("datepicker closed");
  } else { 
    console.log("expansion panel Closed")
  }
});
```

**Comment by jfedoruk** [comment]
@yinonov thanks - the workaround works fine.

**Comment by yinonov** [comment]
Thanks. closing as it's a symptom of #1199
