### ISSUE TITLE
[select] style bug if no label

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid#1250]
**Describe the bug**
select with no label positions the selected option as if it considers a label present.

**To Reproduce**
1. Go to [story](https://vivid.vonage.com/?path=/story/components-select--default)
2. remove the label (from controls)
3. Select an option
4. See the bug

**Expected behavior**
style should be conditioned in css and align the selected option to vertical middle if no label.
note that **dense select should not be affected**

**Screenshots**
<img width="238" alt="image" src="https://user-images.githubusercontent.com/15140652/156512180-aab05965-d971-4eb4-a6e5-8febae0e762b.png">

**Additional context**
[Dense no label](https://vivid.vonage.com/?path=/story/components-select--dense-no-label&args=dense:) features a WCAG violation as form associated element must have a label.

These use cases should instruct consumers of this violation unless compensated by `aria-label` / `aria-labeledby`. should be added to guideline?

**Comment by jshenkman** [comment]
Notice, `Select` component - `dense` variant should have a placeholder text as well. It's not instead of having a label but it should be in addition. 


here are some examples
1. [Carbon](https://www.carbondesignsystem.com/components/select/usage/) 
![Screen Shot 2022-03-03 at 12 00 31](https://user-images.githubusercontent.com/67224525/156541779-f32cd100-9729-48b7-9b61-f22627b0128d.png)
![Screen Shot 2022-03-03 at 12 01 04](https://user-images.githubusercontent.com/67224525/156541854-567754f7-18b1-4285-acbd-321bd0f45b6f.png)

2. [Spectrum](https://opensource.adobe.com/spectrum-web-components/components/picker/)
![Screen Shot 2022-03-03 at 12 01 52](https://user-images.githubusercontent.com/67224525/156541983-855b8fb9-52b6-4eb8-a79b-da2af2e5bf8d.png)
![Screen Shot 2022-03-03 at 12 02 12](https://user-images.githubusercontent.com/67224525/156542036-5d8c2016-bec7-47b3-b69d-c40eff57e869.png)

**Comment by rachelbt** [comment]
there's no place holder in the select component, it present the first option in the inside list.
@yinonov  currently one can add a select with or without a label even it is is a violation.

**Comment by rachelbt** [comment]
StoryBook:
https://tmp.dev.vivid.vonage.com/1251/index.html?path=/story/components-select--default&args=label:;helper:Helper+Text

**Comment by rachelbt** [comment]
@yinonov maybe we need to add an option for "hideLabel" that hides visually the label but keeps the aria-label.

**Comment by yinonov** [comment]
select supports aria-label/labeledby. what's the benefit of it?

**Comment by RoyMenczerVonage** [comment]
Hi,
Can you please update me when this fix is released?
Thanks

**Comment by yinonov** [comment]
> Hi, Can you please update me when this fix is released? Thanks

out https://github.com/Vonage/vivid/blob/master/CHANGELOG.md#2260-2022-03-13

**Comment by RoyMenczerVonage** [comment]
Thanks
