### ISSUE TITLE
[Slider] shows incorrect value in tooltip when setting value property

### ISSUE THREAD

**Issue by JKarwatka** [Vonage/vivid#1345]
**Describe the bug**
When trying to set value property of Vivid Slider, the slider shows correct value but when you hover over to see the tooltip, it shows incorrect value. This issue affects one of our products (User Admin).For more information see the video attached below

**To Reproduce**
1. Go to [Vivid Storybook](https://vivid.vonage.com/?path=/story/components-slider--default&args=value:5;min:1;max:10;step:1;pin:;markers:)
2. Move slider with cursor 
3. Tooltip shows correct value of the slider
4. Change value property in controls section
5. Slider shows correct value but tooltip does not.

**Expected behavior**
Slider and tooltip should show identical value

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 105.0.5195.125

https://user-images.githubusercontent.com/14012988/192790042-bf767022-b31e-41a5-94a0-b1740dc38b02.mov

**Comment by yinonov** [comment]
Thanks for reporting

**Comment by martynfrank** [comment]
@yinonov are we no longer supporting this version of Vivid?

**Comment by yinonov** [comment]
it's [in the works in vivid@next](https://github.com/Vonage/vivid-3/pull/738) already

**Comment by martynfrank** [comment]
@yinonov, I understand that. But to get that fix, we need to upgrade our UI to use a new version of Vivid that I understand is still in beta. We have not yet finished upgrading from Volta to vivid, so a jump to a new version will be a little way out.
Will it be fixed in this version (the major supported version, as I understand it) of vivid?

**Comment by yinonov** [comment]
Vivid next is at the verge of becoming the stable version. 1-2 months.
Other than parity concerns it is much more reliable than its former.

Can you please provide some data on the number of components in your app? Or share its repo?

**Comment by martynfrank** [comment]
@yinonov, this is the VCC product. We have four key UI areas that are built in vivid:
- User Admin
- Business Apps
- Team dashboards
- Analytics

We then have a further 13 UI areas built in Volta.

My big concern is that a push to a new version of Vivid will incur a high cost, and we are yet to pay the debt of deprecating Volta. I expect there is very sound thinking behind the move to vivid next. Is there a write-up of the business case to launch a new version? Also, is there any documentation of what a migration path looks like/will cost?

Is the fact that this bug is not being fixed an indicator that this version of Vivid is deprecated?

**Comment by yinonov** [comment]
the current stable version depends, in its large portion, on the material library.

some of the major issues we faced with material were:

- lack of transparency
- not being driven by community
- opinionated implementations of component often deviating from standard
- not production ready (e.g. controls aren't form associated)

Vivid next relies on the FAST foundation base classes which is in a sense the "responsible" alternative.

The migration results in a better UI for all. it's more reliable, expected, aligns with standards, and scalable.

There's, currently, no migration guide I'll present the new library to VCC very soon. in the meantime u can review the [docs](https://vivid.deno.dev/). the advantage is we are here to help any migration, we are a vonage team and not a 3rd party lib. we prioritise Vonage teams requests.

note that it's not a new library in its interface, rather a breaking changing major version. not so much different than any other library / framework major bump. Vivid started 3 years ago and reaching version 3 now makes all sense. this change has been in the works for a year.

We can check what it'll take to fix the discussed bug in current vivid but it might require tweaking code which no longer exist in material. they drifted away from the components we depend on disregarding backwards compatibility.

**Comment by martynfrank** [comment]
Thanks for taking the time to write all that up. I appreciate it. I had a few thoughts reading:
- As soon as you can write it, a migration guide and breaking change list will be beneficial in judging the cost of migration.
- When you offer help to migrate, what does that mean practically? For example, we have a team building a brand new UI in Vivid. Could someone from your team join them for a few weeks to complete the migration?
- I am aware that no one in VCC knew a new major version has been in the plans for a year. This is an issue; the teams want to contribute their thoughts and views on where we should invest.
- We need formal guidance on the supported version of Vivid and clarity of what support is provided in each stage. This issue is a good example. To fix a slider, the immediate response is to complete an upgrade that implies a level of deprecation.

I am happy if you want to shift this conversation to Slack or Email. I appreciate it now only loosely relates to the issue raised here.

**Comment by yinonov** [comment]
- I don't suppose [CHANGELOG.md](https://github.com/Vonage/vivid-3/blob/main/libs/components/CHANGELOG.md) would be ideal but it's something to start from.
- In terms of migration help - I wouldn't guarantee joining the integration team fully but all of us are keen to help in the process and join the effort in PRs, perhaps create a channel and dedicate a % to the integration milestone.
- I'm not sure why news don't propagate to VCC. are the team members added to [#ask-vivid](https://vonage.slack.com/archives/C013F0YKH99)? we have a short presentation scheduled for the next VCC COI meeting. feedback is very important to Vivid. can you suggest measures to reflect updates to your teams?

please, feel free to message me, or the team, at any point on slack
