### ISSUE TITLE
Flexibility to remove the white border line in vwc-expansion panel

### ISSUE THREAD

**Issue by bchandel77** [Vonage/vivid#1375]
There is no option in vivid right now to remove the white border line as shared in the screenshot.
![image](https://user-images.githubusercontent.com/108921736/226300703-6965cf2c-09be-4d74-832a-178f630ba873.png)

**Comment by olaf-k** [comment]
Hey Barthi. As we explained in Slack, we don't provide such an option because the widget has been designed as you see it.
The goal of a design system is to provide a consistent display across applications. If the designers in your team believe this is a requirement, they should raise it and discuss it with @AyalaBu.
